### ISSUE TITLE
Test final Monero POW cryptonight_v8

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#1851]
Monero is changing there POW in October 2018. Please test the implementation of the new algorithm against the test pool (http://killallasics.moneroworld.com/) 

You can find the source code of xmr-stak in pull request #1831 or [download the zipped source](https://github.com/psychocrypt/xmr-stak/archive/topic-cn-v8_v2.zip)  directly.

Please report here only the speed comparison between `cryptonight_v7` and `cryptonight_v8`. If you fund any bugs please report it in the pull request #1831.
Please also take the time to mine a few minutes against the testnet pool to check that you not get invalid results.

# How to bench the system:
Please start the miner once with `./xmr-stak` to create `pools.txt`and all other config files.
Change `cryptonight_v8` into `cryptonight_v7` to measure the performance of the current monero POW. Please do not forget to remove the backend configs if you switch the algorithm because `"strided_index" : 1` is not allowed for `cryptonight_v8`

## CPU:
```
./xmr-stak  --currency cryptonight_v8 --noAMD --noNVIDIA --benchmark 8 --benchwait  20 --benchwork 30
```

## ~~CUDA~~/AMD OpenCL:
```
./xmr-stak --currency cryptonight_v8  --benchmark 8 --benchwait  20 --benchwork 30
```
**CUDA** is currently not supported. I am currently try to get some performance out it.

## NVIDIA via OpenCL
```
./xmr-stak --currency cryptonight_v8 --openCLVendor NVIDIA --benchmark 8 --benchwait  20 --benchwork 30
```

# Template for speed reporting:
```
OS: XX
Backend: (including the type e.g. AMD RX570)
 - CPU
  - NVIDIA (native CUDA or via OpenCL)
  - AMD 
# if the CPU/GPU is overclocked please add the modifications here
speed:  
 - cryptonight_v7: XXX H/s
 - cryptonight_v8: XXX H/s
Miner config: please add here your config for the backend
```
